### PR TITLE
Changed download URL

### PR DESCRIPTION
**Pull request by wieczorek1990**

### CODE REVIEW

**Comment by wieczorek1990** [comment]
https://github.com/gdamjan/ansible-uwsgi/issues/7

**Comment by DavidWittman** [comment]
:-1: without HTTPS.

Is there any benefit to using this download URL as opposed to Github?

**Comment by wieczorek1990** [comment]
I should have posted a description.
I think it was failing due to https occasionally.

**Comment by gdamjan** [comment]
@wieczorek1990 find out what it is and fix the issue in vagrant. 
there have been problems with the urls at unbit.it in the past, and I'm relucantant to change it.

**Pull request closed without merging**
